name: ESS Contracts nuget workflow

on:
  workflow_dispatch
  #push:
  #  branches:
  #  - master
  #  tags: 'ess.contracts.*'
  #  paths:
  #  - "ess/src/API/EMBC.ESS.Shared.Contracts/**"
  #  - ".github/workflows/release-ess-contracts-nuget.yml"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
        source-url: https://nuget.pkg.github.com/bcgov/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: dotnet build --configuration Release ess/src/API/EMBC.ESS.Shared.Contracts/
    - run: dotnet pack --configuration Release ess/src/API/EMBC.ESS.Shared.Contracts/
    - run: dotnet nuget push ess/src/API/EMBC.ESS.Shared.Contracts/bin/Release/*.nupkg --source "bcgov_github" -k ${{secrets.GITHUB_TOKEN}}
